### ISSUE TITLE
 irsend.sendRaw 

### ISSUE THREAD

**Issue by aknik** [Edzelf/ESP-IR#1]
Lines 128 and 129 must change from:
  unsigned int sndbuf[50] ;
  int          i = 0 ;
----------------------------------------------- to:
  uint16_t     sndbuf[50] ;
  uint16_t          i = 0 ;
-----------------------------------------------
if not , irsend.sendRaw will not work

**Comment by Edzelf** [comment]
Thanks, I will look into it.  Strange thing, as I am using the thing for more than 2 years every day.  Maybe it has something to do with a new library.

**Comment by Edzelf** [comment]
I updated the sketch for IRremoteESP8266 v2.0.
